services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: openpark
      POSTGRES_USER: openpark
      POSTGRES_PASSWORD: openpark
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    environment:
      POSTGRES_DB: openpark_test
      POSTGRES_USER: openpark
      POSTGRES_PASSWORD: openpark
    ports:
      - "5433:5432"

volumes:
  postgres_data:
