"""init redesigned schema

Revision ID: 6361c625a6af
Revises: 
Create Date: 2026-05-13 10:24:58.725956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6361c625a6af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('parking_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('total_spaces', sa.Integer(), nullable=False),
    sa.Column('available_spaces', sa.Integer(), nullable=False),
    sa.Column('base_fee', sa.Integer(), nullable=False),
    sa.Column('base_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('extra_fee_per_unit', sa.Integer(), nullable=False),
    sa.Column('extra_fee_unit_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_max_fee', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_spaces <= total_spaces', name='ck_available_lte_total'),
    sa.CheckConstraint('available_spaces >= 0', name='ck_available_spaces_non_negative'),
    sa.CheckConstraint('total_spaces > 0', name='ck_total_spaces_positive'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('entry_exit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parking_lot_id', sa.UUID(), nullable=False),
    sa.Column('plate_hash', sa.String(length=64), nullable=False),
    sa.Column('plate_enc', sa.LargeBinary(), nullable=False),
    sa.Column('event_type', sa.String(length=5), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('entry', 'exit', 'admin')", name='ck_event_type'),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logs_lot_time', 'entry_exit_logs', ['parking_lot_id', 'client_timestamp'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parking_lot_id', sa.UUID(), nullable=False),
    sa.Column('plate_hash', sa.String(length=64), nullable=False),
    sa.Column('plate_enc', sa.LargeBinary(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parking_lot_id', 'plate_hash', name='uq_vehicle_lot_plate')
    )
    op.create_index('idx_vehicles_lookup', 'vehicles', ['parking_lot_id', 'plate_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vehicles_lookup', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('idx_logs_lot_time', table_name='entry_exit_logs')
    op.drop_table('entry_exit_logs')
    op.drop_table('parking_lots')
    op.drop_table('users')
    # ### end Alembic commands ###
